services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - postgres_rds_db_name=${postgres_rds_db_name}
      - postgres_rds_port=${postgres_rds_port}
      - postgres_rds_username=${postgres_rds_username}
      - postgres_rds_password=${postgres_rds_password}
      - postgres_rds_endpoint=${postgres_rds_endpoint}
      - mysql_rds_endpoint=${mysql_rds_endpoint}
      - mysql_rds_port=${mysql_rds_port}
      - mysql_rds_db_name=${mysql_rds_db_name}
      - mysql_rds_username=${mysql_rds_username}
      - mysql_rds_password=${mysql_rds_password}
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"  
    depends_on:
      config-server:
        condition: service_healthy

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
      
    depends_on:
      config-server:
        condition: service_healthy